# Generated by Django 4.1.7 on 2023-03-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default=True, max_length=150)),
                ('pdescription', models.TextField(default=True, max_length=200)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
